"""Declarative late-bound compatibility exports for the report portal entrypoint."""
from __future__ import annotations

_BINDINGS = (
    ('format_iso_timestamp', 'portal_foundation_runtime', 'format_iso_timestamp'),
    ('now_iso_local', 'portal_foundation_runtime', 'now_iso_local'),
    ('now_iso_utc', 'portal_foundation_runtime', 'now_iso_utc'),
    ('parse_iso_timestamp', 'portal_foundation_runtime', 'parse_iso_timestamp'),
    ('_asset_inventory_module', 'portal_foundation_runtime', 'asset_inventory_module'),
    ('load_asset_inventory_data', 'portal_foundation_runtime', 'load_asset_inventory_data'),
    ('_asset_record_state', 'portal_foundation_runtime', 'asset_record_state'),
    ('_asset_public_record', 'portal_foundation_runtime', 'asset_public_record'),
    ('load_dhcp_asset_discovery_state_data', 'portal_foundation_runtime', 'load_dhcp_asset_discovery_state_data'),
    ('_mac_address_scope', 'portal_foundation_runtime', 'mac_address_scope'),
    ('_annotate_exact_ip_dhcp_macs', 'portal_foundation_runtime', 'annotate_exact_ip_dhcp_macs'),
    ('_dhcp_asset_inventory_overlay', 'portal_foundation_runtime', 'dhcp_asset_inventory_overlay'),
    ('asset_inventory_response', 'portal_foundation_runtime', 'asset_inventory_response'),
    ('software_asset_label_snapshot', 'portal_foundation_runtime', 'software_asset_label_snapshot'),
    ('software_inventory_response', 'portal_foundation_runtime', 'software_inventory_response'),
    ('resolve_asset_ip', 'portal_foundation_runtime', 'resolve_asset_ip'),
    ('dhcp_asset_discovery_response', 'portal_foundation_runtime', 'dhcp_asset_discovery_response'),
    ('pcap_transfer_duration_seconds', 'portal_foundation_runtime', 'pcap_transfer_duration_seconds'),
    ('format_timestamp_text', 'portal_foundation_runtime', 'format_timestamp_text'),
    ('_safe_read_json', 'portal_foundation_runtime', 'safe_read_json'),
    ('_freshest_existing_path', 'portal_foundation_runtime', 'freshest_existing_path'),
    ('n8n_beacon_history_response', 'portal_foundation_runtime', 'n8n_beacon_history_response'),
    ('pcap_workflow_health_response', 'portal_foundation_runtime', 'pcap_workflow_health_response'),
    ('ensure_admin_token', 'portal_access_runtime', 'ensure_admin_token'),
    ('load_admin_password_record', 'portal_access_runtime', 'load_admin_password_record'),
    ('admin_password_configured', 'portal_access_runtime', 'admin_password_configured'),
    ('verify_admin_password', 'portal_access_runtime', 'verify_admin_password'),
    ('admin_session_hash', 'portal_access_runtime', 'admin_session_hash'),
    ('load_admin_sessions', 'portal_access_runtime', 'load_admin_sessions'),
    ('save_admin_sessions', 'portal_access_runtime', 'save_admin_sessions'),
    ('prune_admin_sessions', 'portal_access_runtime', 'prune_admin_sessions'),
    ('create_admin_session', 'portal_access_runtime', 'create_admin_session'),
    ('destroy_admin_session', 'portal_access_runtime', 'destroy_admin_session'),
    ('resource_library_id_for', 'portal_access_runtime', 'resource_library_id_for'),
    ('find_resource_library_pdf', 'portal_access_runtime', 'find_resource_library_pdf'),
    ('unique_destination', 'portal_access_runtime', 'unique_destination'),
    ('refresh_resource_library', 'portal_access_runtime', 'refresh_resource_library'),
    ('load_resource_library_metadata', 'portal_access_runtime', 'load_resource_library_metadata'),
    ('save_resource_library_metadata', 'portal_access_runtime', 'save_resource_library_metadata'),
    ('clean_resource_tags', 'portal_access_runtime', 'clean_resource_tags'),
    ('sanitize_resource_filename', 'portal_access_runtime', 'sanitize_resource_filename'),
    ('queue_resource_action', 'portal_access_runtime', 'queue_resource_action'),
    ('trigger_resource_library_worker', 'portal_access_runtime', 'trigger_resource_library_worker'),
    ('resource_favorites', 'portal_access_runtime', 'resource_favorites'),
    ('set_resource_favorite', 'portal_access_runtime', 'set_resource_favorite'),
    ('set_resource_tags', 'portal_access_runtime', 'set_resource_tags'),
    ('rename_resource_file', 'portal_access_runtime', 'rename_resource_file'),
    ('queue_resource_removal', 'portal_access_runtime', 'queue_resource_removal'),
    ('move_resource_to_removal', 'portal_access_runtime', 'move_resource_to_removal'),
    ('parse_cookie_header', 'portal_access_runtime', 'parse_cookie_header'),
    ('admin_session_cookie_header', 'portal_access_runtime', 'admin_session_cookie_header'),
    ('expired_admin_session_cookie_header', 'portal_access_runtime', 'expired_admin_session_cookie_header'),
    ('read_prompt_file', 'portal_settings_runtime', 'read_prompt_file'),
    ('read_soc_analyst_prompt', 'portal_settings_runtime', 'read_soc_analyst_prompt'),
    ('read_siem_engineer_prompt', 'portal_settings_runtime', 'read_siem_engineer_prompt'),
    ('read_threat_hunter_prompt', 'portal_settings_runtime', 'read_threat_hunter_prompt'),
    ('read_cyber_threat_intel_prompt', 'portal_settings_runtime', 'read_cyber_threat_intel_prompt'),
    ('read_incident_responder_prompt', 'portal_settings_runtime', 'read_incident_responder_prompt'),
    ('read_settings_prompt', 'portal_settings_runtime', 'read_settings_prompt'),
    ('agent_memory_files', 'portal_settings_runtime', 'agent_memory_files'),
    ('read_agent_memory', 'portal_settings_runtime', 'read_agent_memory'),
    ('save_prompt_file', 'portal_settings_runtime', 'save_prompt_file'),
    ('save_soc_analyst_prompt', 'portal_settings_runtime', 'save_soc_analyst_prompt'),
    ('save_siem_engineer_prompt', 'portal_settings_runtime', 'save_siem_engineer_prompt'),
    ('save_threat_hunter_prompt', 'portal_settings_runtime', 'save_threat_hunter_prompt'),
    ('save_cyber_threat_intel_prompt', 'portal_settings_runtime', 'save_cyber_threat_intel_prompt'),
    ('save_incident_responder_prompt', 'portal_settings_runtime', 'save_incident_responder_prompt'),
    ('save_settings_prompt', 'portal_settings_runtime', 'save_settings_prompt'),
    ('normalize_soc_ai_settings', 'portal_settings_runtime', 'normalize_soc_ai_settings'),
    ('maxmind_geoip_database_status', 'portal_settings_runtime', 'maxmind_geoip_database_status'),
    ('maxmind_geoip_databases_status', 'portal_settings_runtime', 'maxmind_geoip_databases_status'),
    ('_enabled_model_routes_for_settings', 'portal_settings_runtime', 'enabled_model_routes_for_settings'),
    ('soc_ai_settings_store_sources', 'portal_settings_runtime', 'soc_ai_settings_store_sources'),
    ('read_soc_ai_settings', 'portal_settings_runtime', 'read_soc_ai_settings'),
    ('list_ollama_models', 'portal_settings_runtime', 'list_ollama_models'),
    ('_ollama_context_length', 'portal_settings_runtime', 'ollama_context_length'),
    ('classify_ollama_model_compatibility', 'portal_settings_runtime', 'classify_ollama_model_compatibility'),
    ('ollama_model_compatibility', 'portal_settings_runtime', 'ollama_model_compatibility'),
    ('ollama_catalog_sources', 'portal_settings_runtime', 'ollama_catalog_sources'),
    ('ollama_models_response', 'portal_settings_runtime', 'ollama_models_response'),
    ('_write_soc_ai_settings', 'portal_settings_runtime', 'write_soc_ai_settings'),
    ('_resolve_cli_harness_for_settings', 'portal_settings_runtime', 'resolve_cli_harness_for_settings'),
    ('_hermes_auth_readiness_error', 'portal_settings_runtime', 'hermes_auth_readiness_error'),
    ('_enabled_cli_harnesses_ready', 'portal_settings_runtime', 'enabled_cli_harnesses_ready'),
    ('save_soc_ai_settings', 'portal_settings_runtime', 'save_soc_ai_settings'),
    ('save_soc_agent_model', 'portal_settings_runtime', 'save_soc_agent_model'),
    ('admin_status_path', 'portal_admin_runtime', 'admin_status_path'),
    ('admin_log_path', 'portal_admin_runtime', 'admin_log_path'),
    ('process_is_running', 'portal_admin_runtime', 'process_is_running'),
    ('_admin_action_state_sources', 'portal_admin_runtime', 'admin_action_state_sources'),
    ('read_admin_action_status', 'portal_admin_runtime', 'read_admin_action_status'),
    ('write_admin_action_status', 'portal_admin_runtime', 'write_admin_action_status'),
    ('latest_admin_action_outcome', 'portal_admin_runtime', 'latest_admin_action_outcome'),
    ('read_admin_lock', 'portal_admin_runtime', 'read_admin_lock'),
    ('running_admin_action', 'portal_admin_runtime', 'running_admin_action'),
    ('claim_admin_action_lock', 'portal_admin_runtime', 'claim_admin_action_lock'),
    ('update_admin_action_lock_pid', 'portal_admin_runtime', 'update_admin_action_lock_pid'),
    ('release_admin_action_lock', 'portal_admin_runtime', 'release_admin_action_lock'),
    ('start_admin_action', 'portal_admin_runtime', 'start_admin_action'),
    ('tail_file', 'portal_admin_runtime', 'tail_file'),
    ('_cron_failure_sources', 'portal_admin_runtime', 'cron_failure_sources'),
    ('cron_failure_records', 'portal_admin_runtime', 'cron_failure_records'),
    ('render_cron_failure_log_section', 'portal_admin_runtime', 'render_cron_failure_log_section'),
    ('_run_admin_version_command', 'portal_admin_runtime', 'run_admin_version_command'),
    ('admin_action_version_info', 'portal_admin_runtime', 'admin_action_version_info'),
    ('check_admin_action_available', 'portal_admin_runtime', 'check_admin_action_available'),
    ('local_ip', 'portal_catalog_runtime', 'local_ip'),
    ('title_from_html', 'portal_catalog_runtime', 'title_from_html'),
    ('category_for', 'portal_catalog_runtime', 'category_for'),
    ('should_skip_dir', 'portal_catalog_runtime', 'should_skip_dir'),
    ('report_id', 'portal_catalog_runtime', 'report_id'),
    ('scan_reports', 'portal_catalog_runtime', 'scan_reports'),
    ('soc_alerts_report', 'portal_catalog_runtime', 'soc_alerts_report'),
    ('soc_alerts_default_path', 'portal_catalog_runtime', 'soc_alerts_default_path'),
    ('is_daily_threat_brief_file', 'portal_catalog_runtime', 'is_daily_threat_brief_file'),
    ('human_size', 'portal_catalog_runtime', 'human_size'),
    ('artifact_library_disk_usage', 'portal_catalog_runtime', 'artifact_library_disk_usage'),
    ('_admin_process_lines', 'portal_admin_runtime', 'admin_process_lines'),
    ('_admin_service_probe_sources', 'portal_admin_runtime', 'admin_service_probe_sources'),
    ('process_matches', 'portal_admin_runtime', 'process_matches'),
    ('macs_fan_control_status', 'portal_admin_runtime', 'macs_fan_control_status'),
    ('codex_app_status', 'portal_admin_runtime', 'codex_app_status'),
    ('codex_cli_status', 'portal_admin_runtime', 'codex_cli_status'),
    ('docker_status', 'portal_admin_runtime', 'docker_status'),
    ('n8n_container_status', 'portal_admin_runtime', 'n8n_container_status'),
    ('admin_service_statuses', 'portal_admin_runtime', 'admin_service_statuses'),
    ('start_admin_service', 'portal_admin_runtime', 'start_admin_service'),
    ('defang_admin_service_json', 'portal_admin_runtime', 'defang_admin_service_json'),
    ('system_uptime_metric', 'portal_operational_runtime', 'system_uptime_metric'),
    ('local_disk_usage_metric', 'portal_operational_runtime', 'local_disk_usage_metric'),
    ('_directory_disk_scan', 'portal_operational_runtime', 'directory_disk_scan'),
    ('_file_disk_scan', 'portal_operational_runtime', 'file_disk_scan'),
    ('local_disk_inventory', 'portal_operational_runtime', 'local_disk_inventory'),
    ('disk_inventory_rows', 'portal_operational_runtime', 'disk_inventory_rows'),
    ('disk_file_inventory_rows', 'portal_operational_runtime', 'disk_file_inventory_rows'),
    ('hermes_backup_sources', 'portal_operational_runtime', 'hermes_backup_sources'),
    ('latest_hermes_backup_metric', 'portal_operational_runtime', 'latest_hermes_backup_metric'),
    ('macos_update_metric', 'portal_operational_runtime', 'macos_update_metric'),
    ('_brew_update_check', 'portal_operational_runtime', 'brew_update_check'),
    ('_hermes_update_check', 'portal_operational_runtime', 'hermes_update_check'),
    ('update_health_sources', 'portal_operational_runtime', 'update_health_sources'),
    ('brew_update_source_metric', 'portal_operational_runtime', 'brew_update_source_metric'),
    ('hermes_update_source_metric', 'portal_operational_runtime', 'hermes_update_source_metric'),
    ('latest_running_update_action', 'portal_operational_runtime', 'latest_running_update_action'),
    ('latest_update_action_failure', 'portal_operational_runtime', 'latest_update_action_failure'),
    ('prioritized_updates_metric', 'portal_operational_runtime', 'prioritized_updates_metric'),
    ('human_time', 'portal_operational_runtime', 'human_time'),
    ('update_time_label', 'portal_operational_runtime', 'update_time_label'),
    ('relative_time_label', 'portal_operational_runtime', 'relative_time_label'),
    ('admin_last_performed_label', 'portal_operational_runtime', 'admin_last_performed_label'),
    ('portal_last_updated', 'portal_operational_runtime', 'portal_last_updated'),
    ('schedule_label', 'portal_operational_runtime', 'schedule_label'),
    ('next_run_label', 'portal_operational_runtime', 'next_run_label'),
    ('load_cron_summaries', 'portal_operational_runtime', 'load_cron_summaries'),
    ('render_cron_menu', 'portal_operational_runtime', 'render_cron_menu'),
    ('render_cron_item', 'portal_operational_runtime', 'render_cron_item'),
    ('icon_for', 'portal_operational_runtime', 'icon_for'),
    ('redact_sensitive_text', 'portal_operational_runtime', 'redact_sensitive_text'),
    ('read_macos_update_status', 'portal_operational_runtime', 'read_macos_update_status'),
    ('backup_inventory', 'portal_dashboard_runtime', 'backup_inventory'),
    ('metric_detail_shell', 'portal_dashboard_runtime', 'metric_detail_shell'),
    ('render_macos_updates_detail', 'portal_dashboard_runtime', 'render_macos_updates_detail'),
    ('render_prioritized_updates_detail', 'portal_dashboard_runtime', 'render_prioritized_updates_detail'),
    ('render_hermes_backups_detail', 'portal_dashboard_runtime', 'render_hermes_backups_detail'),
    ('render_system_uptime_detail', 'portal_dashboard_runtime', 'render_system_uptime_detail'),
    ('render_local_disk_detail', 'portal_dashboard_runtime', 'render_local_disk_detail'),
    ('render_portal_update_detail', 'portal_dashboard_runtime', 'render_portal_update_detail'),
    ('render_admin_login', 'portal_dashboard_runtime', 'render_admin_login'),
    ('render_admin_dashboard', 'portal_dashboard_runtime', 'render_admin_dashboard'),
    ('render_home', 'portal_dashboard_runtime', 'render_home'),
    ('normalize_soc_alert_status_meta', 'portal_soc_detail_runtime', 'normalize_soc_alert_status_meta'),
    ('ensure_soc_alert_status_table', 'portal_soc_detail_runtime', 'ensure_soc_alert_status_table'),
    ('soc_alert_group_key_from_values', 'portal_soc_detail_runtime', 'soc_alert_group_key_from_values'),
    ('soc_alert_group_id', 'portal_soc_detail_runtime', 'soc_alert_group_id'),
    ('soc_alert_group_key_sql', 'portal_soc_detail_runtime', 'soc_alert_group_key_sql'),
    ('soc_alert_public_enrichment_status', 'portal_soc_detail_runtime', 'soc_alert_public_enrichment_status'),
    ('soc_alert_group_enrichment_json', 'portal_soc_detail_runtime', 'soc_alert_group_enrichment_json'),
    ('soc_alert_group_enrichment_json_map', 'portal_soc_detail_runtime', 'soc_alert_group_enrichment_json_map'),
    ('directory_size_bytes', 'portal_soc_detail_runtime', 'directory_size_bytes'),
    ('soc_alert_validate_detail_layout_html', 'portal_soc_detail_runtime', 'soc_alert_validate_detail_layout_html'),
    ('soc_alert_layout_error_html', 'portal_soc_detail_runtime', 'soc_alert_layout_error_html'),
    ('soc_alert_append_live_pcap_detail', 'portal_soc_detail_runtime', 'soc_alert_append_live_pcap_detail'),
    ('soc_alert_normalize_heading_text', 'portal_soc_detail_runtime', 'soc_alert_normalize_heading_text'),
    ('soc_alert_collapse_detail_sections', 'portal_soc_detail_runtime', 'soc_alert_collapse_detail_sections'),
    ('soc_alert_has_parsed_pcap', 'portal_soc_pcap_runtime', 'soc_alert_has_parsed_pcap'),
    ('read_artifact_cache', 'portal_soc_pcap_runtime', 'read_artifact_cache'),
    ('write_artifact_cache', 'portal_soc_pcap_runtime', 'write_artifact_cache'),
    ('_soc_pcap_artifact_sources', 'portal_soc_pcap_runtime', 'soc_pcap_artifact_sources'),
    ('soc_alert_pcap_analysis_index', 'portal_soc_pcap_runtime', 'soc_alert_pcap_analysis_index'),
    ('soc_alert_pcap_request_statuses', 'portal_soc_pcap_runtime', 'soc_alert_pcap_request_statuses'),
    ('soc_alert_pcap_status', 'portal_soc_pcap_runtime', 'soc_alert_pcap_status'),
    ('soc_alert_pcap_analysis_record', 'portal_soc_pcap_runtime', 'soc_alert_pcap_analysis_record'),
    ('soc_alert_pcap_summary_html', 'portal_soc_pcap_runtime', 'soc_alert_pcap_summary_html'),
    ('sqlite_table_exists', 'portal_soc_pcap_runtime', 'sqlite_table_exists'),
    ('sqlite_table_columns', 'portal_soc_pcap_runtime', 'sqlite_table_columns'),
    ('bounded_int', 'portal_soc_pcap_runtime', 'bounded_int'),
    ('pcap_request_id', 'portal_soc_pcap_runtime', 'pcap_request_id'),
    ('normalize_pcap_timestamp', 'portal_soc_pcap_runtime', 'normalize_pcap_timestamp'),
    ('pcap_capture_file_from_json', 'portal_soc_pcap_runtime', 'pcap_capture_file_from_json'),
    ('pcap_request_store_sources', 'portal_soc_pcap_runtime', 'pcap_request_store_sources'),
    ('pcap_request_candidate_from_group', 'portal_soc_pcap_runtime', 'pcap_request_candidate_from_group'),
    ('pcap_request_policy_sources', 'portal_soc_pcap_runtime', 'pcap_request_policy_sources'),
    ('normalize_pcap_request', 'portal_soc_pcap_runtime', 'normalize_pcap_request'),
    ('insert_pcap_request', 'portal_soc_pcap_runtime', 'insert_pcap_request'),
    ('pcap_request_service_sources', 'portal_soc_pcap_runtime', 'pcap_request_service_sources'),
    ('soc_alert_pcap_request_response', 'portal_soc_pcap_runtime', 'soc_alert_pcap_request_response'),
    ('asset_store_write_token', 'portal_write_runtime', 'asset_store_write_token'),
    ('asset_store_post_json', 'portal_write_runtime', 'asset_store_post_json'),
    ('alert_store_post_json', 'portal_write_runtime', 'alert_store_post_json'),
    ('_normalized_asset_review_payload', 'portal_write_runtime', 'normalized_asset_review_payload'),
    ('_clear_asset_inventory_cache', 'portal_write_runtime', 'clear_asset_inventory_cache'),
    ('asset_dhcp_promotion_response', 'portal_write_runtime', 'asset_dhcp_promotion_response'),
    ('asset_dhcp_ip_change_response', 'portal_write_runtime', 'asset_dhcp_ip_change_response'),
    ('_normalized_asset_mutation_payload', 'portal_write_runtime', 'normalized_asset_mutation_payload'),
    ('asset_update_response', 'portal_write_runtime', 'asset_update_response'),
    ('asset_demote_response', 'portal_write_runtime', 'asset_demote_response'),
    ('dispatch_asset_write', 'portal_write_runtime', 'dispatch_asset_write'),
    ('portal_cti_program_callbacks', 'portal_write_runtime', 'portal_cti_program_callbacks'),
    ('alert_store_get_json', 'portal_write_runtime', 'alert_store_get_json'),
    ('soc_alert_group_summary_available', 'portal_soc_status_runtime', 'soc_alert_group_summary_available'),
    ('soc_alert_group_counts', 'portal_soc_status_runtime', 'soc_alert_group_counts'),
    ('soc_alert_manually_escalated_group_ids', 'portal_soc_status_runtime', 'soc_alert_manually_escalated_group_ids'),
    ('soc_alert_active_group_ids', 'portal_soc_status_runtime', 'soc_alert_active_group_ids'),
    ('soc_alert_status_store_sources', 'portal_soc_status_runtime', 'soc_alert_status_store_sources'),
    ('normalize_soc_group_statuses', 'portal_soc_status_runtime', 'normalize_soc_group_statuses'),
    ('soc_alert_status_persistence_sources', 'portal_soc_status_runtime', 'soc_alert_status_persistence_sources'),
    ('load_soc_alert_statuses_from_db', 'portal_soc_status_runtime', 'load_soc_alert_statuses_from_db'),
    ('write_soc_alert_status_json_snapshot', 'portal_soc_status_runtime', 'write_soc_alert_status_json_snapshot'),
    ('save_soc_alert_statuses_to_db', 'portal_soc_status_runtime', 'save_soc_alert_statuses_to_db'),
    ('load_soc_alert_statuses', 'portal_soc_status_runtime', 'load_soc_alert_statuses'),
    ('save_soc_alert_statuses', 'portal_soc_status_runtime', 'save_soc_alert_statuses'),
    ('current_soc_alert_group_repeat_count', 'portal_soc_status_runtime', 'current_soc_alert_group_repeat_count'),
    ('write_soc_alert_status', 'portal_soc_status_runtime', 'write_soc_alert_status'),
    ('soc_alert_status_response', 'portal_soc_status_runtime', 'soc_alert_status_response'),
    ('llm_analysis_log_limit', 'portal_llm_runtime', 'llm_analysis_log_limit'),
    ('llm_analysis_log_page', 'portal_llm_runtime', 'llm_analysis_log_page'),
    ('read_llm_analysis_logs', 'portal_llm_runtime', 'read_llm_analysis_logs'),
    ('current_llm_queue_size', 'portal_llm_runtime', 'current_llm_queue_size'),
    ('read_bounded_llm_analysis_record', 'portal_llm_runtime', 'read_bounded_llm_analysis_record'),
    ('active_llm_analysis_record_paths', 'portal_llm_runtime', 'active_llm_analysis_record_paths'),
    ('active_llm_sources', 'portal_llm_runtime', 'active_llm_sources'),
    ('read_active_llm_analyses', 'portal_llm_runtime', 'read_active_llm_analyses'),
    ('llm_agent_execution_state', 'portal_llm_runtime', 'llm_agent_execution_state'),
    ('decorate_llm_analysis_record', 'portal_llm_runtime', 'decorate_llm_analysis_record'),
    ('read_llm_current_analysis', 'portal_llm_runtime', 'read_llm_current_analysis'),
    ('merge_live_llm_activity', 'portal_llm_runtime', 'merge_live_llm_activity'),
    ('llm_analysis_process_commands', 'portal_llm_runtime', 'llm_analysis_process_commands'),
    ('llm_analysis_process_active', 'portal_llm_runtime', 'llm_analysis_process_active'),
    ('llm_history_store_sources', 'portal_llm_runtime', 'llm_history_store_sources'),
    ('_llm_analysis_run_timestamp', 'portal_llm_runtime', 'llm_analysis_run_timestamp'),
    ('_llm_primary_run_identity', 'portal_llm_runtime', 'llm_primary_run_identity'),
    ('read_llm_database_primary_logs', 'portal_llm_runtime', 'read_llm_database_primary_logs'),
    ('reconcile_llm_primary_logs', 'portal_llm_runtime', 'reconcile_llm_primary_logs'),
    ('_llm_reviewer_started_at', 'portal_llm_runtime', 'llm_reviewer_started_at'),
    ('hydrate_llm_reviewer_from_parent', 'portal_llm_runtime', 'hydrate_llm_reviewer_from_parent'),
    ('read_llm_second_opinion_logs', 'portal_llm_runtime', 'read_llm_second_opinion_logs'),
    ('read_llm_disagreement_adjudication_logs', 'portal_llm_runtime', 'read_llm_disagreement_adjudication_logs'),
    ('_llm_log_sort_timestamp', 'portal_llm_runtime', 'llm_log_sort_timestamp'),
    ('llm_history_api_sources', 'portal_llm_runtime', 'llm_history_api_sources'),
    ('read_llm_agent_activity_snapshot', 'portal_llm_runtime', 'read_llm_agent_activity_snapshot'),
    ('llm_analysis_logs_response', 'portal_llm_runtime', 'llm_analysis_logs_response'),
    ('soc_alert_suppression_review_state', 'portal_soc_core_runtime', 'soc_alert_suppression_review_state'),
    ('soc_alert_status_write_sources', 'portal_soc_core_runtime', 'soc_alert_status_write_sources'),
    ('update_soc_alert_status', 'portal_soc_core_runtime', 'update_soc_alert_status'),
    ('valid_soc_alert_store_id', 'portal_soc_core_runtime', 'valid_soc_alert_store_id'),
    ('soc_alert_api_error', 'portal_soc_core_runtime', 'soc_alert_api_error'),
    ('soc_alert_db_connect', 'portal_soc_core_runtime', 'soc_alert_db_connect'),
    ('soc_alert_db_write_connect', 'portal_soc_core_runtime', 'soc_alert_db_write_connect'),
    ('parse_soc_alert_since', 'portal_soc_core_runtime', 'parse_soc_alert_since'),
    ('soc_alert_level_names', 'portal_soc_core_runtime', 'soc_alert_level_names'),
    ('soc_alert_row_level', 'portal_soc_core_runtime', 'soc_alert_row_level'),
    ('soc_alert_visible_severity_summary', 'portal_soc_core_runtime', 'soc_alert_visible_severity_summary'),
    ('soc_alert_limit', 'portal_soc_core_runtime', 'soc_alert_limit'),
    ('soc_alert_page', 'portal_soc_core_runtime', 'soc_alert_page'),
    ('soc_alert_sort_clause', 'portal_soc_core_runtime', 'soc_alert_sort_clause'),
    ('soc_alert_cursor_parts', 'portal_soc_core_runtime', 'soc_alert_cursor_parts'),
    ('soc_alert_row_to_api', 'portal_soc_record_runtime', 'soc_alert_row_to_api'),
    ('soc_alert_static_ai_reports', 'portal_soc_record_runtime', 'soc_alert_static_ai_reports'),
    ('_soc_ai_artifact_sources', 'portal_soc_record_runtime', 'soc_ai_artifact_sources'),
    ('soc_alert_latest_prompt_mtime', 'portal_soc_record_runtime', 'soc_alert_latest_prompt_mtime'),
    ('soc_alert_latest_analysis_mtime', 'portal_soc_record_runtime', 'soc_alert_latest_analysis_mtime'),
    ('soc_alert_ai_artifact_index', 'portal_soc_record_runtime', 'soc_alert_ai_artifact_index'),
    ('_soc_ai_group_members', 'portal_soc_record_runtime', 'soc_ai_group_members'),
    ('soc_alert_page_ai_artifact_context', 'portal_soc_record_runtime', 'soc_alert_page_ai_artifact_context'),
    ('soc_alert_group_has_analysis_artifact', 'portal_soc_record_runtime', 'soc_alert_group_has_analysis_artifact'),
    ('soc_alert_severity_meets_analysis_threshold', 'portal_soc_record_runtime', 'soc_alert_severity_meets_analysis_threshold'),
    ('soc_alert_group_ai_status', 'portal_soc_record_runtime', 'soc_alert_group_ai_status'),
    ('soc_alert_detection_outcome_label', 'portal_soc_record_runtime', 'soc_alert_detection_outcome_label'),
    ('_soc_review_epoch', 'portal_soc_record_runtime', 'soc_review_epoch'),
    ('soc_alert_apply_review_metadata', 'portal_soc_record_runtime', 'soc_alert_apply_review_metadata'),
    ('soc_alert_review_state_for_group', 'portal_soc_record_runtime', 'soc_alert_review_state_for_group'),
    ('soc_alert_apply_incident_metadata', 'portal_soc_record_runtime', 'soc_alert_apply_incident_metadata'),
    ('soc_alert_group_evidence_metadata', 'portal_soc_record_runtime', 'soc_alert_group_evidence_metadata'),
    ('soc_alert_group_row_to_api', 'portal_soc_record_runtime', 'soc_alert_group_row_to_api'),
    ('soc_alert_group_representative_alert_id', 'portal_soc_record_runtime', 'soc_alert_group_representative_alert_id'),
    ('_forward_controlled_dispatch_contract', 'portal_incident_action_runtime', 'forward_controlled_dispatch_contract'),
    ('soc_action_service_sources', 'portal_incident_action_runtime', 'soc_action_service_sources'),
    ('soc_alert_queue_analysis_response', 'portal_incident_action_runtime', 'soc_alert_queue_analysis_response'),
    ('soc_alert_escalate_response', 'portal_incident_action_runtime', 'soc_alert_escalate_response'),
    ('_soc_legacy_verdict_factors', 'portal_incident_action_runtime', 'soc_legacy_verdict_factors'),
    ('_soc_derive_legacy_detection_outcome', 'portal_incident_action_runtime', 'soc_derive_legacy_detection_outcome'),
    ('_soc_adjudication_verdict_contradictions', 'portal_incident_action_runtime', 'soc_adjudication_verdict_contradictions'),
    ('normalize_soc_adjudication_payload', 'portal_incident_action_runtime', 'normalize_soc_adjudication_payload'),
    ('_soc_alert_store_mutation', 'portal_incident_action_runtime', 'soc_alert_store_mutation'),
    ('soc_alert_adjudication_response', 'portal_incident_action_runtime', 'soc_alert_adjudication_response'),
    ('_soc_incident_case_group_id', 'portal_incident_action_runtime', 'soc_incident_case_group_id'),
    ('soc_incident_adjudication_response', 'portal_incident_action_runtime', 'soc_incident_adjudication_response'),
    ('soc_incident_status_response', 'portal_incident_action_runtime', 'soc_incident_status_response'),
    ('soc_incident_reanalysis_response', 'portal_incident_action_runtime', 'soc_incident_reanalysis_response'),
    ('soc_incident_bulk_reanalysis_response', 'portal_incident_action_runtime', 'soc_incident_bulk_reanalysis_response'),
    ('soc_incident_reanalysis_runs_response', 'portal_incident_action_runtime', 'soc_incident_reanalysis_runs_response'),
    ('soc_incident_current_analysis', 'portal_incident_action_runtime', 'soc_incident_current_analysis'),
    ('soc_adjudication_history_sources', 'portal_incident_action_runtime', 'soc_adjudication_history_sources'),
    ('soc_adjudication_history_response', 'portal_incident_action_runtime', 'soc_adjudication_history_response'),
    ('soc_incident_agent_display_state', 'portal_incident_action_runtime', 'soc_incident_agent_display_state'),
    ('soc_incidents_query_response', 'portal_incident_read_runtime', 'soc_incidents_query_response'),
    ('soc_incident_review_state', 'portal_incident_read_runtime', 'soc_incident_review_state'),
    ('_incident_html_text', 'portal_incident_read_runtime', 'incident_html_text'),
    ('_incident_nonnegative_int', 'portal_incident_read_runtime', 'incident_nonnegative_int'),
    ('_incident_query_linked_finding', 'portal_incident_read_runtime', 'incident_query_linked_finding'),
    ('_incident_html_list', 'portal_incident_read_runtime', 'incident_html_list'),
    ('_incident_report_section', 'portal_incident_read_runtime', 'incident_report_section'),
    ('render_analyst_review_panel', 'portal_incident_read_runtime', 'render_analyst_review_panel'),
    ('render_investigation_query_audit_html', 'portal_incident_read_runtime', 'render_investigation_query_audit_html'),
    ('render_incident_response_report_html', 'portal_incident_read_runtime', 'render_incident_response_report_html'),
    ('render_prior_soc_analysis_html', 'portal_incident_read_runtime', 'render_prior_soc_analysis_html'),
    ('incident_read_service_sources', 'portal_incident_read_runtime', 'incident_read_service_sources'),
    ('soc_incident_detail_response', 'portal_incident_read_runtime', 'soc_incident_detail_response'),
    ('soc_alert_status_bucket_counts', 'portal_soc_query_runtime', 'soc_alert_status_bucket_counts'),
    ('soc_alert_top_endpoint_metrics', 'portal_soc_query_runtime', 'soc_alert_top_endpoint_metrics'),
    ('soc_alert_group_id_for_query_row', 'portal_soc_query_runtime', 'soc_alert_group_id_for_query_row'),
    ('soc_alert_enriched_page_rows', 'portal_soc_query_runtime', 'soc_alert_enriched_page_rows'),
    ('soc_alert_group_query_snapshot', 'portal_soc_query_runtime', 'soc_alert_group_query_snapshot'),
    ('soc_alert_group_query_payload', 'portal_soc_query_runtime', 'soc_alert_group_query_payload'),
    ('_soc_analysis_min_severity', 'portal_soc_query_runtime', 'soc_analysis_min_severity'),
    ('_soc_group_page_evidence', 'portal_soc_query_runtime', 'soc_group_page_evidence'),
    ('soc_alert_group_query_request', 'portal_soc_query_runtime', 'soc_alert_group_query_request'),
    ('soc_alerts_summary_query_response', 'portal_soc_query_runtime', 'soc_alerts_summary_query_response'),
    ('soc_alerts_query_response', 'portal_soc_query_runtime', 'soc_alerts_query_response'),
    ('cached_soc_alerts_query_response', 'portal_soc_query_runtime', 'cached_soc_alerts_query_response'),
    ('soc_alert_detail_fragment_response', 'portal_soc_query_runtime', 'soc_alert_detail_fragment_response'),
    ('soc_alert_detail_response', 'portal_soc_query_runtime', 'soc_alert_detail_response'),
    ('soc_alert_metrics_response', 'portal_soc_query_runtime', 'soc_alert_metrics_response'),
    ('soc_alert_suppressions_response', 'portal_soc_query_runtime', 'soc_alert_suppressions_response'),
    ('read_soc_alert_json_file', 'portal_delivery_runtime', 'read_soc_alert_json_file'),
    ('soc_alert_events_snapshot', 'portal_delivery_runtime', 'soc_alert_events_snapshot'),
    ('asset_inventory_live_revision', 'portal_delivery_runtime', 'asset_inventory_live_revision'),
    ('dhcp_asset_discovery_live_revision', 'portal_delivery_runtime', 'dhcp_asset_discovery_live_revision'),
    ('software_inventory_live_revision', 'portal_delivery_runtime', 'software_inventory_live_revision'),
    ('incident_response_live_revision', 'portal_delivery_runtime', 'incident_response_live_revision'),
    ('dashboard_live_revisions', 'portal_delivery_runtime', 'dashboard_live_revisions'),
    ('ac_hunter_live_revision', 'portal_delivery_runtime', 'ac_hunter_live_revision'),
    ('cached_soc_alert_events_snapshot', 'portal_delivery_runtime', 'cached_soc_alert_events_snapshot'),
    ('ack_soc_alert_store_id', 'portal_delivery_runtime', 'ack_soc_alert_store_id'),
    ('portal_soc_read_callbacks', 'portal_delivery_runtime', 'portal_soc_read_callbacks'),
    ('portal_general_read_callbacks', 'portal_delivery_runtime', 'portal_general_read_callbacks'),
    ('portal_json_write_callbacks', 'portal_delivery_runtime', 'portal_json_write_callbacks'),

)


_RUNTIME_MARKERS = (
    "_FOUNDATION_RUNTIME", "_ACCESS_RUNTIME", "_SETTINGS_RUNTIME",
    "_ADMIN_RUNTIME", "_CATALOG_RUNTIME", "_OPERATIONAL_RUNTIME",
    "_DASHBOARD_RUNTIME", "_SOC_DETAIL_RUNTIME", "_SOC_PCAP_RUNTIME",
    "_WRITE_RUNTIME", "_SOC_STATUS_RUNTIME", "_LLM_RUNTIME",
    "_SOC_CORE_RUNTIME", "_SOC_RECORD_RUNTIME",
    "_INCIDENT_ACTION_RUNTIME", "_INCIDENT_READ_RUNTIME",
    "_SOC_QUERY_RUNTIME", "_DELIVERY_RUNTIME",
)


def bind(r):
    """Install compatibility delegates and per-portal mutable runtime state."""
    _bind_delegates(r)
    _bind_runtime_markers(r)
    _initialize_portal_state(r)
    _initialize_soc_constants(r)
    _initialize_portal_callbacks(r)


def _bind_delegates(r):
    for public_name, module_name, target_name in _BINDINGS:
        module = getattr(r, module_name)
        setattr(r, public_name, r.partial(getattr(module, target_name), r))


def _bind_runtime_markers(r):
    for marker in _RUNTIME_MARKERS:
        setattr(r, marker, r)


def _initialize_portal_state(r):
    r.SOC_AI_SETTINGS_LOCK = r.threading.RLock()
    r.ADMIN_SERVICE_LABELS = {
        "macs-fan-control": "Macs Fan Control", "codex": "Codex app",
        "codex-cli": "Codex CLI", "docker": "Docker", "n8n": "n8n container",
    }
    r.DISK_INVENTORY_CACHE = {
        "generated": 0.0, "dirs": [], "files": [], "warnings": []
    }
    r.SOC_ALERT_DETAIL_LAYOUT_VERSION = "2026-07-15.1"
    r.SOC_ALERT_DETAIL_LAYOUT_MARKERS = (
        ("alert identity", "<h2>["),
        ("triage reasons", "detail-section-triage-reasons"),
        ("duplicate alert timeline", "alert-timeline-section"),
        ("ai analysis output", "detail-section-ai-analysis-output"),
        ("ai model used", "detail-section-ai-model-used"),
        ("enriched alert details", "detail-section-enriched-alert-details"),
        ("alert summary", "detail-section-alert-summary"),
        ("analyst notes", "detail-section-analyst-notes"),
        ("parsed pcap evidence", "detail-section-parsed-pcap-evidence"),
        ("network and flow details", "detail-section-network-and-flow-details"),
        ("protocol details", "detail-section-protocol-details"),
        ("host and sensor details", "detail-section-host-and-sensor-details"),
        ("threat context", "detail-section-threat-context"),
        ("security onion detail fields", "detail-section-security-onion-detail-fields"),
        ("raw logs", "detail-section-raw-logs"),
    )
    r.SOC_ALERT_COLLAPSIBLE_DETAIL_SECTIONS = {
        "ai model used": "AI Model Used", "alert summary": "Alert Summary",
        "network and flow details": "Network And Flow Details",
        "tshark findings": "TShark Findings",
        "tshark corroboration": "TShark Findings",
        "protocol details": "Protocol Details",
        "host and sensor details": "Host And Sensor Details",
        "threat context": "Threat Context", "analyst notes": "Analyst Notes",
    }
    r.LLM_ANALYSIS_COMBINED_HISTORY_LIMIT = 5000
    r.LLM_AGENT_ACTIVITY_CACHE = r.ResponseCache(3.0, max_entries=1, lock_stripes=1)


def _initialize_soc_constants(r):
    r.SOC_ALERT_SORT_SQL = {
        "count": "COALESCE(total_seen_count, raw_alert_count, seen_count, 0)",
        "severity": "CASE lower(coalesce(triage_level, severity_label, 'informational')) WHEN 'critical' THEN 5 WHEN 'high' THEN 4 WHEN 'medium' THEN 3 WHEN 'low' THEN 2 WHEN 'informational' THEN 1 WHEN 'info' THEN 1 ELSE 0 END",
        "last_seen": "replace(replace(COALESCE(last_seen, timestamp, first_seen), 'T', ' '), 'Z', '')",
        "alert": "lower(coalesce(rule_name, ''))",
        "source_ip": "lower(coalesce(source_ip, ''))",
        "destination_ip": "lower(coalesce(destination_ip, ''))",
        "destination_port": "CAST(COALESCE(destination_port, '') AS INTEGER)",
        "ai": "'not-queued'", "enrichment": "'none'", "pcap": "'none'",
        "log_source": "lower(coalesce(event_dataset, ''))",
        "size": "COALESCE(payload_size_bytes, 0)",
        "risk": "COALESCE(triage_score, 0)",
    }
    r.SOC_ALERT_DETECTION_OUTCOME_LABELS = {
        "true_positive_malicious": "TP - Malicious",
        "true_positive_suspicious": "TP - Suspicious",
        "true_positive_authorized_benign": "TP - Benign",
        "true_positive_benign": "TP - Benign",
        "false_positive_logic_rule": "FP - Rule",
        "false_positive_data_parser": "FP - Parser",
        "false_positive_bad_intel_ioc": "FP - Bad Intel",
        "false_negative": "False Negative", "duplicate": "Duplicate",
        "informational_no_action": "Informational", "inconclusive": "Inconclusive",
    }


def _initialize_portal_callbacks(r):
    r.INCIDENT_ROW_CALLBACKS = r.IncidentRowCallbacks(
        epoch=r._soc_review_epoch, embedded_reviewer=r._soc_embedded_reviewer,
        final_review_status=r._soc_review_final_status,
        outcome_label=r.soc_alert_detection_outcome_label,
        agent_display_state=r.soc_incident_agent_display_state,
        reviewer_authorization=r._soc_reviewer_automation_authorization,
        resolve_asset_ip=r.resolve_asset_ip,
    )
    r.PORTAL_SOC_WRITE_CALLBACKS = r.SocWriteCallbacks(
        alert_ack=r.ack_soc_alert_store_id,
        alert_pcap=r.soc_alert_pcap_request_response,
        alert_analyze=r.soc_alert_queue_analysis_response,
        alert_escalate=r.soc_alert_escalate_response,
        alert_adjudicate=r.soc_alert_adjudication_response,
        incident_adjudicate=r.soc_incident_adjudication_response,
        incident_status=r.soc_incident_status_response,
        incident_reanalyze=r.soc_incident_reanalysis_response,
        incident_reanalyze_all=r.soc_incident_bulk_reanalysis_response,
    )
    r.PortalHandler = r.build_portal_handler(r.BaseHTTPRequestHandler, lambda: r)
